/** Dial countries catalog (ISO 3166-1 alpha-2 + E.164 dial). No third-party dep. */
export type DialCountry = {
  iso2: string;
  dial: string;
  nameEs: string;
  nameEn: string;
};

export const DIAL_COUNTRIES: readonly DialCountry[] = [
  { iso2: 'AF', dial: '+93', nameEs: "Afganistán", nameEn: "Afghanistan" },
  { iso2: 'AL', dial: '+355', nameEs: "Albania", nameEn: "Albania" },
  { iso2: 'DZ', dial: '+213', nameEs: "Argelia", nameEn: "Algeria" },
  { iso2: 'AS', dial: '+1684', nameEs: "Samoa Americana", nameEn: "American Samoa" },
  { iso2: 'AD', dial: '+376', nameEs: "Andorra", nameEn: "Andorra" },
  { iso2: 'AO', dial: '+244', nameEs: "Angola", nameEn: "Angola" },
  { iso2: 'AI', dial: '+1264', nameEs: "Anguila", nameEn: "Anguilla" },
  { iso2: 'AG', dial: '+1268', nameEs: "Antigua y Barbuda", nameEn: "Antigua and Barbuda" },
  { iso2: 'AR', dial: '+54', nameEs: "Argentina", nameEn: "Argentina" },
  { iso2: 'AM', dial: '+374', nameEs: "Armenia", nameEn: "Armenia" },
  { iso2: 'AW', dial: '+297', nameEs: "Aruba", nameEn: "Aruba" },
  { iso2: 'AU', dial: '+61', nameEs: "Australia", nameEn: "Australia" },
  { iso2: 'AT', dial: '+43', nameEs: "Austria", nameEn: "Austria" },
  { iso2: 'AZ', dial: '+994', nameEs: "Azerbaiyán", nameEn: "Azerbaijan" },
  { iso2: 'BS', dial: '+1242', nameEs: "Bahamas", nameEn: "Bahamas" },
  { iso2: 'BH', dial: '+973', nameEs: "Baréin", nameEn: "Bahrain" },
  { iso2: 'BD', dial: '+880', nameEs: "Bangladés", nameEn: "Bangladesh" },
  { iso2: 'BB', dial: '+1246', nameEs: "Barbados", nameEn: "Barbados" },
  { iso2: 'BY', dial: '+375', nameEs: "Bielorrusia", nameEn: "Belarus" },
  { iso2: 'BE', dial: '+32', nameEs: "Bélgica", nameEn: "Belgium" },
  { iso2: 'BZ', dial: '+501', nameEs: "Belice", nameEn: "Belize" },
  { iso2: 'BJ', dial: '+229', nameEs: "Benín", nameEn: "Benin" },
  { iso2: 'BM', dial: '+1441', nameEs: "Bermudas", nameEn: "Bermuda" },
  { iso2: 'BT', dial: '+975', nameEs: "Bután", nameEn: "Bhutan" },
  { iso2: 'BO', dial: '+591', nameEs: "Bolivia", nameEn: "Bolivia" },
  { iso2: 'BA', dial: '+387', nameEs: "Bosnia y Herzegovina", nameEn: "Bosnia and Herzegovina" },
  { iso2: 'BW', dial: '+267', nameEs: "Botsuana", nameEn: "Botswana" },
  { iso2: 'BR', dial: '+55', nameEs: "Brasil", nameEn: "Brazil" },
  { iso2: 'IO', dial: '+246', nameEs: "Territorio Británico del Océano Índico", nameEn: "British Indian Ocean Territory" },
  { iso2: 'VG', dial: '+1284', nameEs: "Islas Vírgenes Británicas", nameEn: "British Virgin Islands" },
  { iso2: 'BN', dial: '+673', nameEs: "Brunéi", nameEn: "Brunei" },
  { iso2: 'BG', dial: '+359', nameEs: "Bulgaria", nameEn: "Bulgaria" },
  { iso2: 'BF', dial: '+226', nameEs: "Burkina Faso", nameEn: "Burkina Faso" },
  { iso2: 'BI', dial: '+257', nameEs: "Burundi", nameEn: "Burundi" },
  { iso2: 'KH', dial: '+855', nameEs: "Camboya", nameEn: "Cambodia" },
  { iso2: 'CM', dial: '+237', nameEs: "Camerún", nameEn: "Cameroon" },
  { iso2: 'CA', dial: '+1', nameEs: "Canadá", nameEn: "Canada" },
  { iso2: 'CV', dial: '+238', nameEs: "Cabo Verde", nameEn: "Cape Verde" },
  { iso2: 'KY', dial: '+1345', nameEs: "Islas Caimán", nameEn: "Cayman Islands" },
  { iso2: 'CF', dial: '+236', nameEs: "República Centroafricana", nameEn: "Central African Republic" },
  { iso2: 'TD', dial: '+235', nameEs: "Chad", nameEn: "Chad" },
  { iso2: 'CL', dial: '+56', nameEs: "Chile", nameEn: "Chile" },
  { iso2: 'CN', dial: '+86', nameEs: "China", nameEn: "China" },
  { iso2: 'CO', dial: '+57', nameEs: "Colombia", nameEn: "Colombia" },
  { iso2: 'KM', dial: '+269', nameEs: "Comoras", nameEn: "Comoros" },
  { iso2: 'CG', dial: '+242', nameEs: "Congo", nameEn: "Congo" },
  { iso2: 'CD', dial: '+243', nameEs: "Congo (RDC)", nameEn: "Congo (DRC)" },
  { iso2: 'CK', dial: '+682', nameEs: "Islas Cook", nameEn: "Cook Islands" },
  { iso2: 'CR', dial: '+506', nameEs: "Costa Rica", nameEn: "Costa Rica" },
  { iso2: 'CI', dial: '+225', nameEs: "Costa de Marfil", nameEn: "Côte d'Ivoire" },
  { iso2: 'HR', dial: '+385', nameEs: "Croacia", nameEn: "Croatia" },
  { iso2: 'CU', dial: '+53', nameEs: "Cuba", nameEn: "Cuba" },
  { iso2: 'CW', dial: '+599', nameEs: "Curazao", nameEn: "Curaçao" },
  { iso2: 'CY', dial: '+357', nameEs: "Chipre", nameEn: "Cyprus" },
  { iso2: 'CZ', dial: '+420', nameEs: "Chequia", nameEn: "Czechia" },
  { iso2: 'DK', dial: '+45', nameEs: "Dinamarca", nameEn: "Denmark" },
  { iso2: 'DJ', dial: '+253', nameEs: "Yibuti", nameEn: "Djibouti" },
  { iso2: 'DM', dial: '+1767', nameEs: "Dominica", nameEn: "Dominica" },
  { iso2: 'DO', dial: '+1809', nameEs: "República Dominicana", nameEn: "Dominican Republic" },
  { iso2: 'EC', dial: '+593', nameEs: "Ecuador", nameEn: "Ecuador" },
  { iso2: 'EG', dial: '+20', nameEs: "Egipto", nameEn: "Egypt" },
  { iso2: 'SV', dial: '+503', nameEs: "El Salvador", nameEn: "El Salvador" },
  { iso2: 'GQ', dial: '+240', nameEs: "Guinea Ecuatorial", nameEn: "Equatorial Guinea" },
  { iso2: 'ER', dial: '+291', nameEs: "Eritrea", nameEn: "Eritrea" },
  { iso2: 'EE', dial: '+372', nameEs: "Estonia", nameEn: "Estonia" },
  { iso2: 'SZ', dial: '+268', nameEs: "Esuatini", nameEn: "Eswatini" },
  { iso2: 'ET', dial: '+251', nameEs: "Etiopía", nameEn: "Ethiopia" },
  { iso2: 'FK', dial: '+500', nameEs: "Islas Malvinas", nameEn: "Falkland Islands" },
  { iso2: 'FO', dial: '+298', nameEs: "Islas Feroe", nameEn: "Faroe Islands" },
  { iso2: 'FJ', dial: '+679', nameEs: "Fiyi", nameEn: "Fiji" },
  { iso2: 'FI', dial: '+358', nameEs: "Finlandia", nameEn: "Finland" },
  { iso2: 'FR', dial: '+33', nameEs: "Francia", nameEn: "France" },
  { iso2: 'GF', dial: '+594', nameEs: "Guayana Francesa", nameEn: "French Guiana" },
  { iso2: 'PF', dial: '+689', nameEs: "Polinesia Francesa", nameEn: "French Polynesia" },
  { iso2: 'GA', dial: '+241', nameEs: "Gabón", nameEn: "Gabon" },
  { iso2: 'GM', dial: '+220', nameEs: "Gambia", nameEn: "Gambia" },
  { iso2: 'GE', dial: '+995', nameEs: "Georgia", nameEn: "Georgia" },
  { iso2: 'DE', dial: '+49', nameEs: "Alemania", nameEn: "Germany" },
  { iso2: 'GH', dial: '+233', nameEs: "Ghana", nameEn: "Ghana" },
  { iso2: 'GI', dial: '+350', nameEs: "Gibraltar", nameEn: "Gibraltar" },
  { iso2: 'GR', dial: '+30', nameEs: "Grecia", nameEn: "Greece" },
  { iso2: 'GL', dial: '+299', nameEs: "Groenlandia", nameEn: "Greenland" },
  { iso2: 'GD', dial: '+1473', nameEs: "Granada", nameEn: "Grenada" },
  { iso2: 'GP', dial: '+590', nameEs: "Guadalupe", nameEn: "Guadeloupe" },
  { iso2: 'GU', dial: '+1671', nameEs: "Guam", nameEn: "Guam" },
  { iso2: 'GT', dial: '+502', nameEs: "Guatemala", nameEn: "Guatemala" },
  { iso2: 'GN', dial: '+224', nameEs: "Guinea", nameEn: "Guinea" },
  { iso2: 'GW', dial: '+245', nameEs: "Guinea-Bisáu", nameEn: "Guinea-Bissau" },
  { iso2: 'GY', dial: '+592', nameEs: "Guyana", nameEn: "Guyana" },
  { iso2: 'HT', dial: '+509', nameEs: "Haití", nameEn: "Haiti" },
  { iso2: 'HN', dial: '+504', nameEs: "Honduras", nameEn: "Honduras" },
  { iso2: 'HK', dial: '+852', nameEs: "Hong Kong", nameEn: "Hong Kong" },
  { iso2: 'HU', dial: '+36', nameEs: "Hungría", nameEn: "Hungary" },
  { iso2: 'IS', dial: '+354', nameEs: "Islandia", nameEn: "Iceland" },
  { iso2: 'IN', dial: '+91', nameEs: "India", nameEn: "India" },
  { iso2: 'ID', dial: '+62', nameEs: "Indonesia", nameEn: "Indonesia" },
  { iso2: 'IR', dial: '+98', nameEs: "Irán", nameEn: "Iran" },
  { iso2: 'IQ', dial: '+964', nameEs: "Irak", nameEn: "Iraq" },
  { iso2: 'IE', dial: '+353', nameEs: "Irlanda", nameEn: "Ireland" },
  { iso2: 'IL', dial: '+972', nameEs: "Israel", nameEn: "Israel" },
  { iso2: 'IT', dial: '+39', nameEs: "Italia", nameEn: "Italy" },
  { iso2: 'JM', dial: '+1876', nameEs: "Jamaica", nameEn: "Jamaica" },
  { iso2: 'JP', dial: '+81', nameEs: "Japón", nameEn: "Japan" },
  { iso2: 'JO', dial: '+962', nameEs: "Jordania", nameEn: "Jordan" },
  { iso2: 'KZ', dial: '+7', nameEs: "Kazajistán", nameEn: "Kazakhstan" },
  { iso2: 'KE', dial: '+254', nameEs: "Kenia", nameEn: "Kenya" },
  { iso2: 'KI', dial: '+686', nameEs: "Kiribati", nameEn: "Kiribati" },
  { iso2: 'XK', dial: '+383', nameEs: "Kosovo", nameEn: "Kosovo" },
  { iso2: 'KW', dial: '+965', nameEs: "Kuwait", nameEn: "Kuwait" },
  { iso2: 'KG', dial: '+996', nameEs: "Kirguistán", nameEn: "Kyrgyzstan" },
  { iso2: 'LA', dial: '+856', nameEs: "Laos", nameEn: "Laos" },
  { iso2: 'LV', dial: '+371', nameEs: "Letonia", nameEn: "Latvia" },
  { iso2: 'LB', dial: '+961', nameEs: "Líbano", nameEn: "Lebanon" },
  { iso2: 'LS', dial: '+266', nameEs: "Lesoto", nameEn: "Lesotho" },
  { iso2: 'LR', dial: '+231', nameEs: "Liberia", nameEn: "Liberia" },
  { iso2: 'LY', dial: '+218', nameEs: "Libia", nameEn: "Libya" },
  { iso2: 'LI', dial: '+423', nameEs: "Liechtenstein", nameEn: "Liechtenstein" },
  { iso2: 'LT', dial: '+370', nameEs: "Lituania", nameEn: "Lithuania" },
  { iso2: 'LU', dial: '+352', nameEs: "Luxemburgo", nameEn: "Luxembourg" },
  { iso2: 'MO', dial: '+853', nameEs: "Macao", nameEn: "Macao" },
  { iso2: 'MG', dial: '+261', nameEs: "Madagascar", nameEn: "Madagascar" },
  { iso2: 'MW', dial: '+265', nameEs: "Malaui", nameEn: "Malawi" },
  { iso2: 'MY', dial: '+60', nameEs: "Malasia", nameEn: "Malaysia" },
  { iso2: 'MV', dial: '+960', nameEs: "Maldivas", nameEn: "Maldives" },
  { iso2: 'ML', dial: '+223', nameEs: "Malí", nameEn: "Mali" },
  { iso2: 'MT', dial: '+356', nameEs: "Malta", nameEn: "Malta" },
  { iso2: 'MH', dial: '+692', nameEs: "Islas Marshall", nameEn: "Marshall Islands" },
  { iso2: 'MQ', dial: '+596', nameEs: "Martinica", nameEn: "Martinique" },
  { iso2: 'MR', dial: '+222', nameEs: "Mauritania", nameEn: "Mauritania" },
  { iso2: 'MU', dial: '+230', nameEs: "Mauricio", nameEn: "Mauritius" },
  { iso2: 'MX', dial: '+52', nameEs: "México", nameEn: "Mexico" },
  { iso2: 'FM', dial: '+691', nameEs: "Micronesia", nameEn: "Micronesia" },
  { iso2: 'MD', dial: '+373', nameEs: "Moldavia", nameEn: "Moldova" },
  { iso2: 'MC', dial: '+377', nameEs: "Mónaco", nameEn: "Monaco" },
  { iso2: 'MN', dial: '+976', nameEs: "Mongolia", nameEn: "Mongolia" },
  { iso2: 'ME', dial: '+382', nameEs: "Montenegro", nameEn: "Montenegro" },
  { iso2: 'MS', dial: '+1664', nameEs: "Montserrat", nameEn: "Montserrat" },
  { iso2: 'MA', dial: '+212', nameEs: "Marruecos", nameEn: "Morocco" },
  { iso2: 'MZ', dial: '+258', nameEs: "Mozambique", nameEn: "Mozambique" },
  { iso2: 'MM', dial: '+95', nameEs: "Myanmar", nameEn: "Myanmar" },
  { iso2: 'NA', dial: '+264', nameEs: "Namibia", nameEn: "Namibia" },
  { iso2: 'NR', dial: '+674', nameEs: "Nauru", nameEn: "Nauru" },
  { iso2: 'NP', dial: '+977', nameEs: "Nepal", nameEn: "Nepal" },
  { iso2: 'NL', dial: '+31', nameEs: "Países Bajos", nameEn: "Netherlands" },
  { iso2: 'NC', dial: '+687', nameEs: "Nueva Caledonia", nameEn: "New Caledonia" },
  { iso2: 'NZ', dial: '+64', nameEs: "Nueva Zelanda", nameEn: "New Zealand" },
  { iso2: 'NI', dial: '+505', nameEs: "Nicaragua", nameEn: "Nicaragua" },
  { iso2: 'NE', dial: '+227', nameEs: "Níger", nameEn: "Niger" },
  { iso2: 'NG', dial: '+234', nameEs: "Nigeria", nameEn: "Nigeria" },
  { iso2: 'NU', dial: '+683', nameEs: "Niue", nameEn: "Niue" },
  { iso2: 'KP', dial: '+850', nameEs: "Corea del Norte", nameEn: "North Korea" },
  { iso2: 'MK', dial: '+389', nameEs: "Macedonia del Norte", nameEn: "North Macedonia" },
  { iso2: 'NO', dial: '+47', nameEs: "Noruega", nameEn: "Norway" },
  { iso2: 'OM', dial: '+968', nameEs: "Omán", nameEn: "Oman" },
  { iso2: 'PK', dial: '+92', nameEs: "Pakistán", nameEn: "Pakistan" },
  { iso2: 'PW', dial: '+680', nameEs: "Palaos", nameEn: "Palau" },
  { iso2: 'PS', dial: '+970', nameEs: "Palestina", nameEn: "Palestine" },
  { iso2: 'PA', dial: '+507', nameEs: "Panamá", nameEn: "Panama" },
  { iso2: 'PG', dial: '+675', nameEs: "Papúa Nueva Guinea", nameEn: "Papua New Guinea" },
  { iso2: 'PY', dial: '+595', nameEs: "Paraguay", nameEn: "Paraguay" },
  { iso2: 'PE', dial: '+51', nameEs: "Perú", nameEn: "Peru" },
  { iso2: 'PH', dial: '+63', nameEs: "Filipinas", nameEn: "Philippines" },
  { iso2: 'PL', dial: '+48', nameEs: "Polonia", nameEn: "Poland" },
  { iso2: 'PT', dial: '+351', nameEs: "Portugal", nameEn: "Portugal" },
  { iso2: 'PR', dial: '+1787', nameEs: "Puerto Rico", nameEn: "Puerto Rico" },
  { iso2: 'QA', dial: '+974', nameEs: "Catar", nameEn: "Qatar" },
  { iso2: 'RE', dial: '+262', nameEs: "Reunión", nameEn: "Réunion" },
  { iso2: 'RO', dial: '+40', nameEs: "Rumanía", nameEn: "Romania" },
  { iso2: 'RU', dial: '+7', nameEs: "Rusia", nameEn: "Russia" },
  { iso2: 'RW', dial: '+250', nameEs: "Ruanda", nameEn: "Rwanda" },
  { iso2: 'KN', dial: '+1869', nameEs: "San Cristóbal y Nieves", nameEn: "Saint Kitts and Nevis" },
  { iso2: 'LC', dial: '+1758', nameEs: "Santa Lucía", nameEn: "Saint Lucia" },
  { iso2: 'VC', dial: '+1784', nameEs: "San Vicente y las Granadinas", nameEn: "Saint Vincent and the Grenadines" },
  { iso2: 'WS', dial: '+685', nameEs: "Samoa", nameEn: "Samoa" },
  { iso2: 'SM', dial: '+378', nameEs: "San Marino", nameEn: "San Marino" },
  { iso2: 'ST', dial: '+239', nameEs: "Santo Tomé y Príncipe", nameEn: "São Tomé and Príncipe" },
  { iso2: 'SA', dial: '+966', nameEs: "Arabia Saudita", nameEn: "Saudi Arabia" },
  { iso2: 'SN', dial: '+221', nameEs: "Senegal", nameEn: "Senegal" },
  { iso2: 'RS', dial: '+381', nameEs: "Serbia", nameEn: "Serbia" },
  { iso2: 'SC', dial: '+248', nameEs: "Seychelles", nameEn: "Seychelles" },
  { iso2: 'SL', dial: '+232', nameEs: "Sierra Leona", nameEn: "Sierra Leone" },
  { iso2: 'SG', dial: '+65', nameEs: "Singapur", nameEn: "Singapore" },
  { iso2: 'SX', dial: '+1721', nameEs: "Sint Maarten", nameEn: "Sint Maarten" },
  { iso2: 'SK', dial: '+421', nameEs: "Eslovaquia", nameEn: "Slovakia" },
  { iso2: 'SI', dial: '+386', nameEs: "Eslovenia", nameEn: "Slovenia" },
  { iso2: 'SB', dial: '+677', nameEs: "Islas Salomón", nameEn: "Solomon Islands" },
  { iso2: 'SO', dial: '+252', nameEs: "Somalia", nameEn: "Somalia" },
  { iso2: 'ZA', dial: '+27', nameEs: "Sudáfrica", nameEn: "South Africa" },
  { iso2: 'KR', dial: '+82', nameEs: "Corea del Sur", nameEn: "South Korea" },
  { iso2: 'SS', dial: '+211', nameEs: "Sudán del Sur", nameEn: "South Sudan" },
  { iso2: 'ES', dial: '+34', nameEs: "España", nameEn: "Spain" },
  { iso2: 'LK', dial: '+94', nameEs: "Sri Lanka", nameEn: "Sri Lanka" },
  { iso2: 'SD', dial: '+249', nameEs: "Sudán", nameEn: "Sudan" },
  { iso2: 'SR', dial: '+597', nameEs: "Surinam", nameEn: "Suriname" },
  { iso2: 'SE', dial: '+46', nameEs: "Suecia", nameEn: "Sweden" },
  { iso2: 'CH', dial: '+41', nameEs: "Suiza", nameEn: "Switzerland" },
  { iso2: 'SY', dial: '+963', nameEs: "Siria", nameEn: "Syria" },
  { iso2: 'TW', dial: '+886', nameEs: "Taiwán", nameEn: "Taiwan" },
  { iso2: 'TJ', dial: '+992', nameEs: "Tayikistán", nameEn: "Tajikistan" },
  { iso2: 'TZ', dial: '+255', nameEs: "Tanzania", nameEn: "Tanzania" },
  { iso2: 'TH', dial: '+66', nameEs: "Tailandia", nameEn: "Thailand" },
  { iso2: 'TL', dial: '+670', nameEs: "Timor Oriental", nameEn: "Timor-Leste" },
  { iso2: 'TG', dial: '+228', nameEs: "Togo", nameEn: "Togo" },
  { iso2: 'TO', dial: '+676', nameEs: "Tonga", nameEn: "Tonga" },
  { iso2: 'TT', dial: '+1868', nameEs: "Trinidad y Tobago", nameEn: "Trinidad and Tobago" },
  { iso2: 'TN', dial: '+216', nameEs: "Túnez", nameEn: "Tunisia" },
  { iso2: 'TR', dial: '+90', nameEs: "Turquía", nameEn: "Turkey" },
  { iso2: 'TM', dial: '+993', nameEs: "Turkmenistán", nameEn: "Turkmenistan" },
  { iso2: 'TC', dial: '+1649', nameEs: "Islas Turcas y Caicos", nameEn: "Turks and Caicos Islands" },
  { iso2: 'TV', dial: '+688', nameEs: "Tuvalu", nameEn: "Tuvalu" },
  { iso2: 'UG', dial: '+256', nameEs: "Uganda", nameEn: "Uganda" },
  { iso2: 'UA', dial: '+380', nameEs: "Ucrania", nameEn: "Ukraine" },
  { iso2: 'AE', dial: '+971', nameEs: "Emiratos Árabes Unidos", nameEn: "United Arab Emirates" },
  { iso2: 'GB', dial: '+44', nameEs: "Reino Unido", nameEn: "United Kingdom" },
  { iso2: 'US', dial: '+1', nameEs: "Estados Unidos", nameEn: "United States" },
  { iso2: 'UY', dial: '+598', nameEs: "Uruguay", nameEn: "Uruguay" },
  { iso2: 'UZ', dial: '+998', nameEs: "Uzbekistán", nameEn: "Uzbekistan" },
  { iso2: 'VU', dial: '+678', nameEs: "Vanuatu", nameEn: "Vanuatu" },
  { iso2: 'VA', dial: '+379', nameEs: "Ciudad del Vaticano", nameEn: "Vatican City" },
  { iso2: 'VE', dial: '+58', nameEs: "Venezuela", nameEn: "Venezuela" },
  { iso2: 'VN', dial: '+84', nameEs: "Vietnam", nameEn: "Vietnam" },
  { iso2: 'VI', dial: '+1340', nameEs: "Islas Vírgenes de EE. UU.", nameEn: "U.S. Virgin Islands" },
  { iso2: 'YE', dial: '+967', nameEs: "Yemen", nameEn: "Yemen" },
  { iso2: 'ZM', dial: '+260', nameEs: "Zambia", nameEn: "Zambia" },
  { iso2: 'ZW', dial: '+263', nameEs: "Zimbabue", nameEn: "Zimbabwe" },
] as const;

/** Prefer these when several countries share a dial (e.g. +1). */
export const PREFERRED_DIAL_ISO2 = ['CO', 'PA', 'MX', 'US', 'CA', 'ES', 'AR', 'CL', 'PE', 'EC'] as const;
